// @ts-check

// This script generates a JSON file from the content/ directory.
// The file contains information about image aspect ratios, and CSS placeholder data
// Aspect ratios are generated by image-size
// CSS placeholder data is generated by plaiceholder

import { readFile, readdir, writeFile, mkdir } from 'fs/promises';
import { getPlaiceholder } from 'plaiceholder';
import path from 'path';
import sizeOf from 'image-size';

const plaiceholderConfig = {
  size: 16,
}

/**
 * Read image size data inside the /public/static folder.
 * @returns {Promise<object>}
 */
async function getData() {
  const { serialize } = await import('next-mdx-remote/serialize');
  const contentDirectory = path.join(process.cwd(), 'src', 'content');
  const prefixes = ['work', 'document'];

  let allFiles = {};
  
  await Promise.all(prefixes.map(async (prefix) => {
    // Read all files, and get file data
    let files = await readdir(path.join(contentDirectory, prefix));
    files = files.filter((value) => value.endsWith('.mdx'));

    // Get page data
    const pages = await Promise.all(files.map(async (file) => {
      const content = await readFile(path.join(contentDirectory, prefix, file), 'utf-8');
      const { frontmatter } = await serialize(content, {
        parseFrontmatter: true,
      });

      // Compile array of images by reading content
      const imagePathRegex = /\/static\/work\/.+\.(png|jpg|jpeg|gif)/g;
      const images = [...content.matchAll(imagePathRegex)].map((matchValue) => matchValue[0]);

      // Generate image data including sizes and placeholders
      const imageData = await Promise.all(images.map(async (imagePath) => {
        const validImagePath = imagePath;

        const imageBuffer = await readFile(path.join('public', validImagePath));

        const { width, height } = sizeOf(imageBuffer);
        const placeholder = await getPlaiceholder(imageBuffer, plaiceholderConfig);

        return {
          imagePath: validImagePath,
          width,
          height,
          placeholder,
        };
      }));

      const previewImage = frontmatter.previewImage;
      let previewImageSize;
      if (typeof previewImage === 'string') {
        // @ts-ignore
        const { width, height } = await sizeOf(path.join('public', previewImage));
        previewImageSize = {
          width,
          height,
          imagePath: previewImage,
        }
      }

      return {
        id: file.substring(0, file.indexOf('.mdx')),
        prefix: prefix,
        allImages: imageData,
        previewImageSize,
      }
    }));

    allFiles[prefix] = pages;
  }));

  return allFiles;
}

/**
 * Write output into a JSON file in the output/ directory.
 * @param {any} data
 */
async function writeData(data) {
  // Check for output directory
  const exists = (await readdir(path.join(process.cwd(), 'src', 'scripts'))).includes('output');
  if (!exists) {
    await mkdir(path.join(process.cwd(), 'src', 'scripts', 'output'));
  }

  await writeFile(path.join(process.cwd(), 'src', 'scripts', 'output', 'data.json'), JSON.stringify(data));
}

getData()
  .then((value) => {
    writeData(value);
  });