import Image from "next/image"
import { ImageSize } from "./work/[id]/getWork"
import styles from './GalleryItem.module.css'
import utils from '../utils.module.css'
import Link from "next/link"
import generatePlaceholder from '@/helpers/generatePlaceholder'

interface Props {
  /**
   * Image to display in the gallery item.
   * Can be a image in the `public` folder, or a remote image.
   * Remote images must be whitelisted in `next.config.js`.
   */
  imageSrc: string,
  /**
   * Size of the image as generated by the `generateImageSizes` script.
   * This prop is required to determine the aspect ratio of the image,
   * and prevent layout shifts.
   */
  imageSize: ImageSize,
  /**
   * Alt text for the provided image.
   */
  imageAlt: string,
  /**
   * Title to display when hovering, or underneath the image on mobile.
   */
  title: string,
  /**
   * The date displayed under the title.
   */
  date: string,
  /**
   * Description of the gallery item; only displayed on desktop.
   */
  description: string,
  /**
   * Link to navigate to on click.
   */
  href: string,
  /**
   * The ID of the work. Required for generating a placeholder image.
   */
  id: string,
  /**
   * Sizes to pass to the underlying `Image` component.
   * 
   * @see https://nextjs.org/docs/pages/api-reference/components/image#sizes
   */
  sizes: string,
}

/**
 * Gallery item to be displayed on the home page.
 * Displays an image, along with title, date, and description when hovering.
 * On mobile, displays title and date even when not hovering.
 * @param param0
 * @returns
 */
export default async function GalleryItem({
  imageSrc,
  imageSize,
  imageAlt,
  title,
  date,
  description,
  href,
  id,
  sizes,
}: Props) {
  const { css } = await generatePlaceholder(imageSrc, 'work', id)

  return (
    <Link className={styles.container} href={href}>
      {/* Hover information */}
      <div className={styles.hoverContentWrapper}>
        <div className={styles.headingWrapper}>
          <h1>
            <b>
              {title}
            </b>
          </h1>
          <p className={`${utils.monoText} ${utils.smallText}`}>{date}</p>
        </div>
        <p>{description}</p>
      </div>
      {/* Image container */}
      <div className={styles.imageContainer} style={{
        aspectRatio: `${imageSize.width} / ${imageSize.height}`,
      }}>
        <div className={styles.imagePlaceholder} style={css}></div>
        <Image
          src={imageSrc}
          alt={imageAlt}
          fill
          sizes={sizes}
          className={styles.image}
        />
      </div>
      <div className={styles.mobileContentWrapper}>
        <h2>
          <b>
            {title}
          </b>
        </h2>
        <p className={`${utils.monoText} ${utils.smallText}`}>{date}</p>
      </div>
    </Link>
  )
}