import ActionButton from './ActionButton'
import Anchor from './Anchor'
import DesktopSideNavigation from './DesktopSideNavigation'
import InfoOverlay from './InfoOverlay'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/upd1iml.css" />
      </head>
      <body>
        <DesktopSideNavigation
          // onNoteOpen={() => {}}
          // selected={selected}
        />
        {children}
      </body>
    </html>
  )
}
