import DesktopSideNavigation from './DesktopSideNavigation'
import './globals.css'
import styles from './layout.module.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/upd1iml.css" />
      </head>
      <body>
        <div className={styles.rootContainer}>

          <DesktopSideNavigation
          // onNoteOpen={() => {}}
          // selected={selected}
          />
          {children}
        </div>

      </body>
    </html>
  )
}
